import { readFileSync, writeFileSync } from 'node:fs';

const packages = ['@dagrejs/dagre', '@dagrejs/graphlib', 'protobufjs',
  '@protobufjs/aspromise', '@protobufjs/base64', '@protobufjs/eventemitter',
  '@protobufjs/float', '@protobufjs/pool', '@protobufjs/utf8', 'long'];
let text = '# Bundled JavaScript notices\n\nGenerated by `node scripts/notices.mjs`. These libraries are bundled into the executable and exported HTML.\n';
for (const name of packages) {
  const directory = `node_modules/${name}`;
  const metadata = JSON.parse(readFileSync(`${directory}/package.json`, 'utf8'));
  const license = readFileSync(`${directory}/LICENSE`, 'utf8').replaceAll('\r\n', '\n');
  text += `\n## ${name} ${metadata.version}\n\n${license.trim()}\n`;
}
writeFileSync('THIRD_PARTY_NOTICES.md', text);
